{
 "title": "Kerio Connect Mail Server",
 "tags": [
  "kerio",
  "mail",
  "zabbix"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Version/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Kerio Connect: Uptime/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Kerio Connect: Users total/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Kerio Connect: Domains total/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "SSL Cert",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/SSL certificate days remaining .443/"
     },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "License",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/License days remaining/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Mail queue count/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Backup Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Backup age/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  { "title": "Storage & Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Storage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Storage used, in/" },
     "application": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/SMTP response time$/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/IMAP response time$/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/HTTPS response time$/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Store & Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Store size/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Backup size/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Store free space/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  { "title": "Mailflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Inbound / Outbound (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Inbound messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Outbound messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Errors (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Deferred messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Bounced messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Rejected messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Inbound Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Inbound messages, today/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Outbound Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Outbound messages, today/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Rejected / h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Rejected messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  { "title": "Connections & Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Connections (cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/IMAP connections/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/POP3 connections/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Web connections/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/SMTP connections$/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Security",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/SMTP auth failures/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    },
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Spam rejected/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Deferred / h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Deferred messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Bounced / h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Bounced messages, 1h/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Queue Oldest",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Queue oldest message age/" },
     "application": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "schema": 12,
     "evaltype": "0"
    }
   ]
  },
  {
   "title": "Port Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  }
 ]
}