# Zabbix NUT monitoring

UserParameter=nut.ups.status,/usr/local/bin/nut_zabbix.sh status
UserParameter=nut.comm,/usr/local/bin/nut_zabbix.sh comm
UserParameter=nut.battery.charge,/usr/local/bin/nut_zabbix.sh battery.charge
UserParameter=nut.battery.voltage,/usr/local/bin/nut_zabbix.sh battery.voltage
UserParameter=nut.input.voltage,/usr/local/bin/nut_zabbix.sh input.voltage
UserParameter=nut.input.frequency,/usr/local/bin/nut_zabbix.sh input.frequency
UserParameter=nut.output.voltage,/usr/local/bin/nut_zabbix.sh output.voltage
UserParameter=nut.ups.load,/usr/local/bin/nut_zabbix.sh ups.load
