name: Update README.md

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install depends
        run: python -m pip install xmltodict

      - name: Run update script
        run: ./.github/workflows/update_readme.py 
      
      - name: Commit results
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Action Bot"
          git add README.md
          git commit README.md -m 'Re-build README.md' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
